/**
 * VNIT IG '26 — Official Scoring Table
 * All 78 official events with exact position-based points as per rule book.
 *
 * type: 'BRACKET' — Events 1-19 (1v1 elimination: QF→SF→LM→Final across 7 matches)
 *   QF losers (4 teams)  → positions 5-8 (P5–P8 — usually 0)
 *   LM winner            → position 3 (P3)
 *   LM loser             → position 4 (P4)
 *   Final loser          → position 2 (P2)
 *   Final winner         → position 1 (P1)
 *
 * type: 'GROUP' — Events 20-78 (admin assigns ranks 1-8 directly)
 *   Points auto-filled from positions table.
 *
 * Special events:
 *   #61 Flash Mob     — flat 30 pts to every participating department (all 8)
 *   #69 Reel-Pic      — only P1=15, no points for others
 *   #72 Mascot        — all 8 departments get 20 pts each
 *   #63 Peace Rally   — all 8 positions have non-zero points (75→30)
 *   #68 Campus Décor  — all 8 positions have non-zero points (75→40)
 *   #54 Video         — all 8 positions have non-zero points (80→10)
 */

const SCORING_TABLE = [
  // ───────────────────────────────────────────────────────────
  // BRACKET EVENTS (1–19): 1v1 tournament, 7 matches per event
  // ───────────────────────────────────────────────────────────
  {
    eventNumber: 1,
    name: 'Badminton',
    sportId: 'BADMINTON',
    type: 'BRACKET',
    venue: 'Sports Complex',
    category: 'TEAM_SPORT',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 2,
    name: 'Basketball (Boys)',
    sportId: 'BASKETBALL_BOYS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 3,
    name: 'Basketball (Girls)',
    sportId: 'BASKETBALL_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 4,
    name: 'Cricket (Boys)',
    sportId: 'CRICKET_BOYS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 60, 2: 45, 3: 30, 4: 15, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 5,
    name: 'Cricket (Girls)',
    sportId: 'CRICKET_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 6,
    name: 'Football',
    sportId: 'FOOTBALL',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 60, 2: 45, 3: 30, 4: 15, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 7,
    name: 'Futsal (Girls)',
    sportId: 'FUTSAL_GIRLS',
    type: 'BRACKET',
    venue: 'Handball court',
    category: 'TEAM_SPORT',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 8,
    name: 'Lawn Tennis',
    sportId: 'LAWN_TENNIS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 9,
    name: 'Table Tennis',
    sportId: 'TABLE_TENNIS',
    type: 'BRACKET',
    venue: 'Sports Complex',
    category: 'TEAM_SPORT',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 10,
    name: 'Volleyball (Boys)',
    sportId: 'VOLLEYBALL_BOYS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 11,
    name: 'Volleyball (Girls)',
    sportId: 'VOLLEYBALL_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 40, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 12,
    name: 'Throwball (Girls)',
    sportId: 'THROWBALL_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 40, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 13,
    name: 'Kho-Kho (Boys)',
    sportId: 'KHOKHO_BOYS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 14,
    name: 'Kho-Kho (Girls)',
    sportId: 'KHOKHO_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 15,
    name: 'Tug of War',
    sportId: 'TUG_OF_WAR',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 16,
    name: 'Kabaddi (Boys)',
    sportId: 'KABADDI_BOYS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 17,
    name: 'Kabaddi (Girls)',
    sportId: 'KABADDI_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
    notes: '*** Contingent event',
  },
  {
    eventNumber: 18,
    name: 'Handball (Boys)',
    sportId: 'HANDBALL_BOYS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 19,
    name: 'Handball (Girls)',
    sportId: 'HANDBALL_GIRLS',
    type: 'BRACKET',
    venue: 'Ground',
    category: 'TEAM_SPORT',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },

  // ───────────────────────────────────────────────────────────
  // GROUP EVENTS (20–78): admin assigns ranks 1-8 directly
  // ───────────────────────────────────────────────────────────
  {
    eventNumber: 20,
    name: 'Triathlon',
    sportId: 'TRIATHLON',
    type: 'GROUP',
    venue: 'As per Rule Book',
    category: 'ENDURANCE',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 21,
    name: 'Marathon (Boys)',
    sportId: 'MARATHON_BOYS',
    type: 'GROUP',
    venue: 'As per RuleBook',
    category: 'ENDURANCE',
    positions: { 1: 30, 2: 20, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 22,
    name: 'Marathon (Girls)',
    sportId: 'MARATHON_GIRLS',
    type: 'GROUP',
    venue: 'As per RuleBook',
    category: 'ENDURANCE',
    positions: { 1: 30, 2: 20, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 23,
    name: 'Cycling',
    sportId: 'CYCLING',
    type: 'GROUP',
    venue: 'As per RuleBook',
    category: 'ENDURANCE',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 24,
    name: '100m (Boys)',
    sportId: '100M_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 20, 2: 15, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 25,
    name: '100m (Girls)',
    sportId: '100M_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 20, 2: 15, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 26,
    name: '400m (Boys)',
    sportId: '400M_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 20, 2: 15, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 27,
    name: '400m (Girls)',
    sportId: '400M_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 20, 2: 15, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 28,
    name: '800m (Boys)',
    sportId: '800M_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 20, 2: 15, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 29,
    name: '800m (Girls)',
    sportId: '800M_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 20, 2: 15, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 30,
    name: '4×100m Relay (Boys)',
    sportId: '4X100M_RELAY_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 31,
    name: '4×100m Relay (Girls)',
    sportId: '4X100M_RELAY_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 32,
    name: '4×100m Relay (Mixed)',
    sportId: '4X100M_RELAY_MIXED',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_TRACK',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 33,
    name: 'Shot Put (Boys)',
    sportId: 'SHOT_PUT_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_FIELD',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 34,
    name: 'Shot Put (Girls)',
    sportId: 'SHOT_PUT_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_FIELD',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 35,
    name: 'Discus Throw (Boys)',
    sportId: 'DISCUS_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_FIELD',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 36,
    name: 'Discus Throw (Girls)',
    sportId: 'DISCUS_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_FIELD',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 37,
    name: 'Javelin Throw (Boys)',
    sportId: 'JAVELIN_BOYS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_FIELD',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 38,
    name: 'Javelin Throw (Girls)',
    sportId: 'JAVELIN_GIRLS',
    type: 'GROUP',
    venue: 'Ground',
    category: 'ATHLETICS_FIELD',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 39,
    name: 'Swimming 50m (Boys)',
    sportId: 'SWIMMING_50M_BOYS',
    type: 'GROUP',
    venue: 'Swimming Pool',
    category: 'AQUATICS',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 40,
    name: 'Swimming 50m (Girls)',
    sportId: 'SWIMMING_50M_GIRLS',
    type: 'GROUP',
    venue: 'Swimming Pool',
    category: 'AQUATICS',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 41,
    name: 'Counter Strike 2',
    sportId: 'COUNTER_STRIKE',
    type: 'GROUP',
    venue: 'CRC',
    category: 'ESPORTS',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 42,
    name: 'FIFA',
    sportId: 'FIFA',
    type: 'GROUP',
    venue: 'CRC',
    category: 'ESPORTS',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 43,
    name: 'VALORANT',
    sportId: 'VALORANT',
    type: 'GROUP',
    venue: 'CRC',
    category: 'ESPORTS',
    positions: { 1: 40, 2: 30, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 44,
    name: 'BGMI',
    sportId: 'BGMI',
    type: 'GROUP',
    venue: 'CRC',
    category: 'ESPORTS',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 45,
    name: 'CODM',
    sportId: 'CODM',
    type: 'GROUP',
    venue: 'CRC',
    category: 'ESPORTS',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 46,
    name: 'Clash Royale',
    sportId: 'CLASH_ROYALE',
    type: 'GROUP',
    venue: 'CRC',
    category: 'ESPORTS',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 47,
    name: 'Powerlifting',
    sportId: 'POWERLIFTING_BELOW_70',
    type: 'GROUP',
    venue: 'Ground',
    category: 'INDOOR',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
    notes: '* Contingent event',
  },
  {
    eventNumber: 48,
    name: 'Chess',
    sportId: 'CHESS',
    type: 'GROUP',
    venue: 'Sports Complex',
    category: 'INDOOR',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 49,
    name: 'Carrom',
    sportId: 'CARROM',
    type: 'GROUP',
    venue: 'Sports Complex',
    category: 'INDOOR',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 50,
    name: 'Yoga (Boys)',
    sportId: 'YOGA_BOYS',
    type: 'GROUP',
    venue: 'Sports Complex',
    category: 'INDOOR',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 51,
    name: 'Yoga (Girls)',
    sportId: 'YOGA_GIRLS',
    type: 'GROUP',
    venue: 'Sports Complex',
    category: 'INDOOR',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 52,
    name: 'Dramatics Stage',
    sportId: 'DRAMATICS_STAGE',
    type: 'GROUP',
    venue: 'Auditorium',
    category: 'CULTURAL',
    positions: { 1: 75, 2: 60, 3: 40, 4: 20, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 53,
    name: 'Dramatics Street',
    sportId: 'DRAMATICS_STREET',
    type: 'GROUP',
    venue: 'ECE Lawns',
    category: 'CULTURAL',
    positions: { 1: 75, 2: 60, 3: 40, 4: 20, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 54,
    name: 'Video',
    sportId: 'VIDEO',
    type: 'GROUP',
    venue: '-',
    category: 'CULTURAL',
    // All 8 positions have points
    positions: { 1: 80, 2: 60, 3: 50, 4: 40, 5: 30, 6: 20, 7: 15, 8: 10 },
  },
  {
    eventNumber: 55,
    name: 'Impromptu',
    sportId: 'IMPROMPTU',
    type: 'GROUP',
    venue: 'CRC',
    category: 'CULTURAL',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 56,
    name: 'Mime',
    sportId: 'MIME',
    type: 'GROUP',
    venue: 'Auditorium',
    category: 'CULTURAL',
    positions: { 1: 30, 2: 20, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 57,
    name: 'Stage Dance',
    sportId: 'STAGE_DANCE',
    type: 'GROUP',
    venue: 'Auditorium',
    category: 'CULTURAL',
    positions: { 1: 70, 2: 60, 3: 45, 4: 15, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 58,
    name: 'Band',
    sportId: 'BAND',
    type: 'GROUP',
    venue: 'Auditorium',
    category: 'CULTURAL',
    positions: { 1: 70, 2: 65, 3: 45, 4: 15, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 59,
    name: 'Mannequin Challenge',
    sportId: 'MANNEQUIN_CHALLENGE',
    type: 'GROUP',
    venue: '-',
    category: 'CULTURAL',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 60,
    name: 'Meri Marzi (Professor)',
    sportId: 'MERI_MARZI_PROFESSOR',
    type: 'GROUP',
    venue: 'CRC',
    category: 'CULTURAL',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 61,
    name: 'Flash Mob',
    sportId: 'FLASH_MOB',
    type: 'GROUP',
    venue: 'Basketball court',
    category: 'CULTURAL',
    // SPECIAL: All 8 departments get 30 pts each (as per Rule Book)
    positions: { 1: 30, 2: 30, 3: 30, 4: 30, 5: 30, 6: 30, 7: 30, 8: 30 },
    notes: 'All participating departments receive 30 pts (as per Rule Book)',
  },
  {
    eventNumber: 62,
    name: 'Dance Face Off',
    sportId: 'DANCE_FACE_OFF',
    type: 'GROUP',
    venue: 'Basketball court',
    category: 'CULTURAL',
    positions: { 1: 50, 2: 35, 3: 20, 4: 10, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 63,
    name: 'Peace Rally',
    sportId: 'RALLY',
    type: 'GROUP',
    venue: 'Ground',
    category: 'CULTURAL',
    // SPECIAL: All 8 positions have points (30–75)
    positions: { 1: 75, 2: 65, 3: 55, 4: 50, 5: 45, 6: 40, 7: 35, 8: 30 },
    notes: '** All departments competing get points; mandatory participation',
  },
  {
    eventNumber: 64,
    name: 'Cloth Painting',
    sportId: 'CLOTH_PAINTING',
    type: 'GROUP',
    venue: 'MAC',
    category: 'ART',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 65,
    name: 'Rangoli',
    sportId: 'RANGOLI',
    type: 'GROUP',
    venue: 'MAC',
    category: 'ART',
    positions: { 1: 35, 2: 25, 3: 15, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 66,
    name: 'Face Painting',
    sportId: 'FACE_PAINTING',
    type: 'GROUP',
    venue: 'MAC',
    category: 'ART',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 67,
    name: 'Collage',
    sportId: 'COLLAGE',
    type: 'GROUP',
    venue: 'MAC',
    category: 'ART',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 68,
    name: 'Campus Décor',
    sportId: 'CAMPUS_DECOR',
    type: 'GROUP',
    venue: 'Respective allotted positions',
    category: 'ART',
    // SPECIAL: All 8 positions have points (40–75)
    positions: { 1: 75, 2: 70, 3: 65, 4: 60, 5: 55, 6: 50, 7: 45, 8: 40 },
    notes: 'All 8 departments get positions; mandatory campus decoration',
  },
  {
    eventNumber: 69,
    name: 'Reel-Pic of the Day',
    sportId: 'REEL_OF_THE_DAY',
    type: 'GROUP',
    venue: '-',
    category: 'OTHER',
    // SPECIAL: Only P1=15, others=0
    positions: { 1: 15, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
    notes: 'Only best single reel/pic wins; daily recurring event',
  },
  {
    eventNumber: 70,
    name: 'Letter Design',
    sportId: 'LETTER_DESIGN',
    type: 'GROUP',
    venue: '-',
    category: 'LITERARY',
    positions: { 1: 30, 2: 20, 3: 10, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 71,
    name: 'Caricature Designing',
    sportId: 'CARICATURE_DESIGNING',
    type: 'GROUP',
    venue: 'MAC',
    category: 'ART',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 72,
    name: 'Mascot',
    sportId: 'MASCOT',
    type: 'GROUP',
    venue: '-',
    category: 'ART',
    // SPECIAL: All 8 departments get 20 pts each (flat, no ranking)
    positions: { 1: 20, 2: 20, 3: 20, 4: 20, 5: 20, 6: 20, 7: 20, 8: 20 },
    notes: 'All 8 departments receive 20 pts for submitting their mascot',
  },
  {
    eventNumber: 73,
    name: 'JAM',
    sportId: 'JAM',
    type: 'GROUP',
    venue: 'CRC',
    category: 'LITERARY',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 74,
    name: 'Creative Writing',
    sportId: 'CREATIVE_WRITING',
    type: 'GROUP',
    venue: 'CRC',
    category: 'LITERARY',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
    notes: '*4 participants per department allowed',
  },
  {
    eventNumber: 75,
    name: 'Debate',
    sportId: 'DEBATE',
    type: 'GROUP',
    venue: 'CRC',
    category: 'LITERARY',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
    notes: '*3 participants per department allowed',
  },
  {
    eventNumber: 76,
    name: 'Poetry',
    sportId: 'POETRY',
    type: 'GROUP',
    venue: 'CRC',
    category: 'LITERARY',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
    notes: '*3 participants per department allowed',
  },
  {
    eventNumber: 77,
    name: 'Quiz',
    sportId: 'QUIZ',
    type: 'GROUP',
    venue: 'CRC',
    category: 'LITERARY',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
  {
    eventNumber: 78,
    name: 'Newsletter Design',
    sportId: 'NEWSLETTER_DESIGN',
    type: 'GROUP',
    venue: 'As per the Rule Book',
    category: 'LITERARY',
    positions: { 1: 20, 2: 15, 3: 10, 4: 5, 5: 0, 6: 0, 7: 0, 8: 0 },
  },
];

/** Quick lookup by event number */
const byNumber = Object.fromEntries(SCORING_TABLE.map(e => [e.eventNumber, e]));

/** Quick lookup by sportId */
const bySportId = Object.fromEntries(SCORING_TABLE.map(e => [e.sportId, e]));

/** Get points for a given event + position */
function getPoints(eventNumber, position) {
  const entry = byNumber[eventNumber];
  if (!entry) return 0;
  return entry.positions[position] ?? 0;
}

/** Get all bracket events */
function getBracketEvents() {
  return SCORING_TABLE.filter(e => e.type === 'BRACKET');
}

/** Get all group events */
function getGroupEvents() {
  return SCORING_TABLE.filter(e => e.type === 'GROUP');
}

module.exports = {
  SCORING_TABLE,
  byNumber,
  bySportId,
  getPoints,
  getBracketEvents,
  getGroupEvents,
};
